export default [
  {
    id: 1,
    name: 'warehouse one',
    address1: 'address1',
    address2: 'address2',
    address3: 'address3',
    city: 'city',
    state: 'state',
    zip: '1000',
    country: '1',
    phone: '0123456789',
    ext: '',
    fax: '123-456',
    email: 'wearehouseone@example.com',
    is_backup_warehouse: true,
    backup_warehouses: [2, 3],
    shipping_zones: ['Alabama', 'Arkansas'],
    rank: 1,
  },
  {
    id: 2,
    name: 'warehouse two',
    address1: 'address1',
    address2: 'address2',
    address3: 'address3',
    city: 'city',
    state: 'state',
    zip: '1000',
    country: '1',
    phone: '0123456789',
    ext: '',
    fax: '123-456',
    email: 'wearehouseone@example.com',
    is_backup_warehouse: true,
    backup_warehouses: [],
    shipping_zones: ['Alabama', 'Arkansas'],
    rank: 2,
  },
  {
    id: 3,
    name: 'warehouse three',
    address1: 'address1',
    address2: 'address2',
    address3: 'address3',
    city: 'city',
    state: 'state',
    zip: '1000',
    country: '1',
    phone: '0123456789',
    ext: '',
    fax: '123-456',
    email: 'wearehouseone@example.com',
    is_backup_warehouse: true,
    backup_warehouses: [],
    shipping_zones: ['Alabama', 'Arkansas'],
    rank: 3,
  },
];
