export const data = [
  {
    key: 1,
    status: 'active',
    source_warehouse: 'Alex Warehouse',
    order_number: '23232',
    fba_shipment: '',
    created_date: '12/12/2022',
    closed_date: '20/12/2022',
    notes: '',
    sales_channel: 'Internal',
    receiving_warehouse: 'FBA',
    total: '24',
    shipping: '3PL',
    tracking: '23232',
  },
  {
    key: 2,
    status: 'pending_receiving',
    source_warehouse: 'Alex Warehouse',
    order_number: '23232',
    fba_shipment: '',
    created_date: '12/12/2022',
    closed_date: '20/12/2022',
    notes: '',
    sales_channel: 'Internal',
    receiving_warehouse: 'FBA',
    total: '24',
    shipping: '3PL',
    tracking: '23232',
  },
  {
    key: 3,
    status: 'active',
    source_warehouse: 'Alex Warehouse',
    order_number: '23232',
    fba_shipment: '',
    created_date: '12/12/2022',
    closed_date: '20/12/2022',
    notes: '',
    sales_channel: 'Internal',
    receiving_warehouse: 'FBA',
    total: '24',
    shipping: '3PL',
    tracking: '23232',
  },
];

export const historyData = [
  {
    key: 1,
    edit_time: '23-10-2022 02:00:00',
    user: 'Alex',
    description: 'This order is changes',
  },
  {
    key: 2,
    edit_time: '30-10-2022 10:00:00',
    user: 'Alex 2',
    description: 'This order is changes',
  },
];

export const recieveData = [
  {
    key: 1,
    status: 'Complete',
    master_sku: '123323',
    notes: 'This order is changes',
    quantity: '2',
    recieved_location: 'Warehouse',
  },
  {
    key: 2,
    status: 'In progress',
    master_sku: '124354',
    notes: 'This order is changes',
    quantity: '25',
    recieved_location: 'Warehouse',
  },
];
