export const data = [
  {
    key: 1,
    type: 'type1',
    master_sku: 'Spring Bar',
    name: 'Everest Spring Bar',
    brand: 'brand1',
    description: 'description1',
    on_hands: 'on_hands',
    locked: 'locked',
    allocated: '20',
    in_transfer: 'in_transfer',
    available: 'available',
    discrepation: 'discrepation',
    status: 'active',
  },
  {
    key: 2,
    type: 'type2',
    master_sku: 'Buckle',
    name: 'Everest Buckle',
    brand: 'brand2',
    description: 'description2',
    on_hands: 'on_hands',
    locked: 'locked',
    allocated: '40',
    in_transfer: 'in_transfer',
    available: 'available',
    discrepation: 'discrepation',
    status: 'active',
  },
  {
    key: 1,
    type: 'type1',
    master_sku: 'Black Rubber Strap',
    name: 'Everest Strap (Black Rubber)',
    brand: 'brand1',
    description: 'description1',
    on_hands: 'on_hands',
    locked: 'locked',
    allocated: '50',
    in_transfer: 'in_transfer',
    available: 'available',
    discrepation: 'discrepation',
    status: 'active',
  },
  {
    key: 2,
    type: 'type2',
    master_sku: 'Rudysku_4',
    name: 'Toys',
    brand: 'brand2',
    description: 'description2',
    on_hands: 'on_hands',
    locked: 'locked',
    allocated: '60',
    in_transfer: 'in_transfer',
    available: 'available',
    discrepation: 'discrepation',
    status: 'active',
  },
  {
    key: 3,
    type: 'type2',
    master_sku: '222',
    name: 'product2',
    brand: 'brand2',
    description: 'description2',
    on_hands: 'on_hands',
    locked: 'locked',
    allocated: '80',
    in_transfer: 'in_transfer',
    available: 'available',
    discrepation: 'discrepation',
    status: 'active',
  },
];

  export const stock_data = [
    {
      key: 1,
      location: 'Location 1',
      status: 'Active',
      rank: '1',
      min_level: '2',
      available: '100',
    },
    {
      key: 2,
      location: 'Location 2',
      status: 'Active',
      rank: '2',
      min_level: '3',
      available: '200',
    },
    {
      key: 3,
      location: 'Location 3',
      status: 'Active',
      rank: '3',
      min_level: '2',
      available: '200',
    },
  ];

  export const stock_history = [
    {
      key: 1,
      edit_time: '04/09/2021 10:49 AM',
      user: 'support@skubana.com',
      edit_type: 'Adjust',
      description: 'This is test',
      notes: 'Test',
    },
    {
      key: 2,
      edit_time: '04/09/2022',
      user: 'support@test.com',
      edit_type: 'Adjust sf',
      description: 'This is test dv',
      notes: 'Test s',
    },
    {
      key: 3,
      edit_time: '04/09/2022',
      user: 'support23@test.com',
      edit_type: 'Adjust w3',
      description: 'This is test 34',
      notes: 'Test 34',
    },
  ];

export const stock_allocation = [
  {
    key: 1,
    warehouse: 'Jeff Warehouse',
    stock_location: 'Location 1',
    order_number: 'Stock transfer 1',
    allocated: '20',
    picked: '0',
  },
  {
    key: 2,
    warehouse: 'Jeff Warehouse 2',
    stock_location: 'Location 2',
    order_number: 'Stock transfer 2',
    allocated: '50',
    picked: '0',
  },
  {
    key: 3,
    warehouse: 'Jeff Warehouse 3',
    stock_location: 'Location 3',
    order_number: 'Stock transfer 3',
    allocated: '80',
    picked: '0',
  },
];